"""add degraded flags to ai_analyses and businesses

Revision ID: 3ecd0431343a
Revises: 3a5749360a88
Create Date: 2026-08-09 01:30:00

Hand-written rather than autogenerated: this repo's models use PostgreSQL's
JSONB/UUID dialect types directly, which don't compile against SQLite at all
(CompileError: "can't render element of type JSONB") -- there is no local
database autogenerate can diff against for anything past the very first,
from-nothing revision. Two added columns are simple enough to write by hand;
verified via `alembic upgrade head --sql` that the emitted DDL is exactly the
intended ALTER TABLEs.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "3ecd0431343a"
down_revision: str | None = "3a5749360a88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "ai_analyses",
        sa.Column("degraded", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "businesses",
        sa.Column("ai_degraded", sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    op.drop_column("businesses", "ai_degraded")
    op.drop_column("ai_analyses", "degraded")
