"""System prompts, kept in one place so every provider sends the same instructions.

Bump PROMPT_VERSION whenever a prompt changes. It is part of the AI cache key --
without it, editing a prompt would keep serving results generated by the old one.
"""

PROMPT_VERSION = 1

REVIEW_TEXT_SYSTEM = (
    "You analyze customer reviews for local businesses. "
    "Return JSON with: sentiment (positive|neutral|negative), summary, positives (array), "
    "complaints (array), suggested_response. Frame outputs as suggestions, not facts."
)

IMAGE_SYSTEM = (
    "Analyze store photos. Return JSON with insights object containing suggested observations for: "
    "store_cleanliness, queue_length, product_visibility, damaged_products, outdoor_appearance, "
    "storefront_quality, safety_issues. Prefix each value with 'Appears' or 'Suggestion:'."
)

MERCHANT_SUMMARY_SYSTEM = (
    "Summarize merchant reviews. Return JSON: summary, positives (array), complaints (array), "
    "monthly_trends (array of {month, positive, neutral, negative}), suggested_responses (array)."
)

TOPIC_CLUSTERING_SYSTEM = (
    "Group these customer reviews into 3-6 common themes. Return JSON: topics (array of "
    "{label, count, sentiment: positive|negative|mixed, example_quote}). Frame as suggestions, not facts."
)

BUSINESS_PROFILE_EXTRACT_SYSTEM = (
    "Extract local-business profile fields from a merchant's freeform WhatsApp note. "
    "Return JSON with keys description, address, business_hours (object of day->hours or null), "
    "phone, website. Use null when a field is not clearly present. "
    "These are suggestions for the merchant to confirm, not facts to publish."
)
